<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>px4_uavcup_bringup</name>
  <version>0.1.0</version>
  <description>
    Full-vehicle launch files for the Urban UAV Cup Pi stack.
  </description>
  <maintainer email="anh.nguyenvantuan54@hcmut.edu.vn">dolphiinn</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>px4_uavcup_perception</exec_depend>
  <exec_depend>px4_uavcup_control</exec_depend>
  <exec_depend>px4_uavcup_px4_bridge</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
