services:
  ros:
    build:
      context: .
      network: host
    network_mode: host
    ipc: host
    privileged: true
    working_dir: /ros2_ws
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./:/ros2_ws
      - /dev:/dev
      - /home/dolphiinn/models:/models:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
    command: bash

  xrce-agent:
    build:
      context: .
      dockerfile: Dockerfile.xrce-agent
      network: host
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
    command: ["serial", "--dev", "/dev/serial0", "-b", "921600"]
    restart: unless-stopped
